# Generated by Django 5.0.6 on 2024-05-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
